[package]
name = "thames"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
async-trait = "0.1.50"
log = "0.4.22"
strum = "0.26.3"
strum_macros = "0.26.4"
serde = "1.0.209"
